---
apiVersion: v1
kind: Namespace
metadata:
  name: ctf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctf-sa
  namespace: ctf
---
apiVersion: v1
kind: Secret
metadata:
  name: ctf-sa-token
  namespace: ctf
  annotations:
    kubernetes.io/service-account.name: ctf-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf-sa-binding
  namespace: ctf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: ctf-sa
  namespace: ctf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: company-db
  name: company-db
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-db
  strategy: {}
  template:
    metadata:
      labels:
        app: company-db
    spec:
      containers:
      - image: bitnami/postgresql:latest
        name: postgresql
        env:
        - name: POSTGRESQL_PASSWORD
          value: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: company-app-cobra
  name: company-app-cobra
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-app-cobra
  strategy: {}
  template:
    metadata:
      labels:
        app: company-app-cobra
        service: company-app
    spec:
      serviceAccountName: ctf-sa
      containers:
      - image: alexnisulescu/nginx:cobra
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: company-app-viper
  name: company-app-viper
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-app-viper
  strategy: {}
  template:
    metadata:
      labels:
        app: company-app-viper
        service: company-app
    spec:
      serviceAccountName: ctf-sa
      containers:
      - image: alexnisulescu/nginx:viper
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: company-app
  namespace: ctf
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: company-app
  type: LoadBalancer